/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ImageZoomPanPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var PREFIX = "my-custom-zoom-";
var ImageZoomPanPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.overlay = null;
    this.imgElement = null;
    this.zoomState = {
      scale: 1,
      translateX: 0,
      translateY: 0,
      isDragging: false,
      startX: 0,
      startY: 0,
      lastX: 0,
      lastY: 0
    };
    this.animationFrameId = null;
    /**
     * ����ͼƬ����¼�
     */
    this.handleImageClick = (e) => {
      const mouseEvent = e;
      const target = mouseEvent.target;
      if (target.tagName !== "IMG")
        return;
      const isReadingView = target.closest(".markdown-reading-view");
      const isLivePreview = target.closest(".markdown-source-view");
      if (!isReadingView && !isLivePreview)
        return;
      e.preventDefault();
      e.stopPropagation();
      this.showOverlay(target);
    };
    /**
     * ���������¼�
     */
    this.handleKeyDown = (e) => {
      if (e.key === "Escape") {
        this.removeOverlay();
      }
    };
    /**
     * ������������
     */
    this.handleWheel = (e) => {
      e.preventDefault();
      if (!this.overlay || !this.imgElement)
        return;
      const rect = this.imgElement.getBoundingClientRect();
      const mouseX = e.clientX - rect.left;
      const mouseY = e.clientY - rect.top;
      const delta = e.deltaY > 0 ? 0.9 : 1.1;
      const newScale = Math.min(Math.max(this.zoomState.scale * delta, 0.1), 10);
      const scaleChange = newScale / this.zoomState.scale;
      const newTranslateX = mouseX - (mouseX - this.zoomState.translateX) * scaleChange;
      const newTranslateY = mouseY - (mouseY - this.zoomState.translateY) * scaleChange;
      this.zoomState.scale = newScale;
      this.zoomState.translateX = newTranslateX;
      this.zoomState.translateY = newTranslateY;
      this.updateTransform();
    };
    /**
     * ������갴��
     */
    this.handleMouseDown = (e) => {
      if (e.button !== 0)
        return;
      this.zoomState.isDragging = true;
      this.zoomState.startX = e.clientX;
      this.zoomState.startY = e.clientY;
      this.zoomState.lastX = this.zoomState.translateX;
      this.zoomState.lastY = this.zoomState.translateY;
      if (this.imgElement) {
        this.imgElement.classList.add(`${PREFIX}dragging`);
      }
    };
    /**
     * ��������ƶ�
     */
    this.handleMouseMove = (e) => {
      if (!this.zoomState.isDragging)
        return;
      if (this.animationFrameId)
        return;
      this.animationFrameId = requestAnimationFrame(() => {
        const deltaX = e.clientX - this.zoomState.startX;
        const deltaY = e.clientY - this.zoomState.startY;
        this.zoomState.translateX = this.zoomState.lastX + deltaX;
        this.zoomState.translateY = this.zoomState.lastY + deltaY;
        this.updateTransform();
        this.animationFrameId = null;
      });
    };
    /**
     * ��������ͷ�
     */
    this.handleMouseUp = () => {
      this.zoomState.isDragging = false;
      if (this.imgElement) {
        this.imgElement.classList.remove(`${PREFIX}dragging`);
      }
    };
  }
  async onload() {
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        this.setupImageListeners();
      })
    );
    this.setupImageListeners();
  }
  onunload() {
    this.removeOverlay();
  }
  /**
   * ����ͼƬ���������
   */
  setupImageListeners() {
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    leaves.forEach((leaf) => {
      const view = leaf.view;
      if (!view)
        return;
      const container = view.containerEl;
      container.removeEventListener("click", this.handleImageClick);
      container.addEventListener("click", this.handleImageClick);
    });
  }
  /**
   * ��ʾͼƬ�鿴��
   */
  showOverlay(img) {
    this.overlay = document.createElement("div");
    this.overlay.className = `${PREFIX}overlay`;
    const imgContainer = document.createElement("div");
    imgContainer.className = `${PREFIX}img-container`;
    this.imgElement = document.createElement("img");
    this.imgElement.src = img.src;
    this.imgElement.className = `${PREFIX}img`;
    this.zoomState = {
      scale: 1,
      translateX: 0,
      translateY: 0,
      isDragging: false,
      startX: 0,
      startY: 0,
      lastX: 0,
      lastY: 0
    };
    imgContainer.appendChild(this.imgElement);
    this.overlay.appendChild(imgContainer);
    document.body.appendChild(this.overlay);
    this.addOverlayListeners();
    requestAnimationFrame(() => {
      var _a;
      (_a = this.overlay) == null ? void 0 : _a.classList.add(`${PREFIX}visible`);
    });
  }
  /**
   * ���Ӹ��ǲ��¼�����
   */
  addOverlayListeners() {
    if (!this.overlay || !this.imgElement)
      return;
    this.overlay.addEventListener("click", (e) => {
      if (e.target === this.overlay) {
        this.removeOverlay();
      }
    });
    document.addEventListener("keydown", this.handleKeyDown);
    this.overlay.addEventListener("wheel", this.handleWheel, { passive: false });
    this.imgElement.addEventListener("mousedown", this.handleMouseDown);
    document.addEventListener("mousemove", this.handleMouseMove);
    document.addEventListener("mouseup", this.handleMouseUp);
  }
  /**
   * �Ƴ����ǲ��¼�����
   */
  removeOverlayListeners() {
    document.removeEventListener("keydown", this.handleKeyDown);
    document.removeEventListener("mousemove", this.handleMouseMove);
    document.removeEventListener("mouseup", this.handleMouseUp);
    if (this.animationFrameId) {
      cancelAnimationFrame(this.animationFrameId);
      this.animationFrameId = null;
    }
  }
  /**
   * ����ͼƬ�任
   */
  updateTransform() {
    if (!this.imgElement)
      return;
    this.imgElement.style.transform = `translate(${this.zoomState.translateX}px, ${this.zoomState.translateY}px) scale(${this.zoomState.scale})`;
  }
  /**
   * �Ƴ����ǲ�
   */
  removeOverlay() {
    if (!this.overlay)
      return;
    this.removeOverlayListeners();
    this.overlay.classList.remove(`${PREFIX}visible`);
    setTimeout(() => {
      var _a;
      (_a = this.overlay) == null ? void 0 : _a.remove();
      this.overlay = null;
      this.imgElement = null;
    }, 300);
  }
};

/* nosourcemap */