const { chromium } = await import(process.env.DXD_PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
// Run against a disposable browser profile; no filesystem character writes.
const browser=await chromium.launch({ channel: 'chrome', headless: true });
const context=await browser.newContext({viewport:{width:480,height:900}});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
page.on('dialog',d=>d.accept());
const snapshot=()=>page.evaluate(()=>{const x=JSON.parse(localStorage.getItem('dxd-character-library-v1'));const d=x.entries.find(e=>e.id===x.activeId).draft;return {...d,updatedAt:null,characterId:null};});
await page.goto('http://127.0.0.1:3000/',{waitUntil:'networkidle'});
await page.getByRole('button',{name:'Continue',exact:true}).click();
await page.getByText('Assign Demographics',{exact:true}).first().waitFor();
const before=await snapshot();
await page.getByRole('button',{name:'Generate',exact:true}).click();
await page.waitForFunction(()=>{const x=JSON.parse(localStorage.getItem('dxd-character-library-v1'));return !!x.entries.find(e=>e.id===x.activeId).draft.background.sex;});
const after=await snapshot();assert.notDeepEqual(before,after);
assert.ok(await page.getByRole('button',{name:'Undo',exact:true}).isEnabled());
await page.getByRole('button',{name:'Undo',exact:true}).click();assert.deepEqual(await snapshot(),before);
await page.getByRole('button',{name:'Redo',exact:true}).click();assert.deepEqual(await snapshot(),after);
console.log('PASS atomic normalized generation undo/redo');
await page.reload({waitUntil:'networkidle'});
assert.ok(await page.getByRole('button',{name:'Undo',exact:true}).isEnabled());
await page.getByRole('button',{name:'Undo',exact:true}).click();assert.deepEqual(await snapshot(),before);
await page.getByRole('navigation',{name:'Character views',exact:true}).getByRole('link',{name:'Profile',exact:true}).click();
await page.waitForURL('**/profile');await page.getByRole('button',{name:'Redo',exact:true}).click();assert.deepEqual(await snapshot(),after);
console.log('PASS persistence reload and cross-view history');
const sizes=await page.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('dxd-character-history-v1:')).map(k=>new TextEncoder().encode(localStorage[k]).length));assert.ok(sizes.length&&sizes.every(n=>n<10000));
await page.locator('summary[aria-label="Workspace menu"]').click();await page.getByLabel('Remember undo history').uncheck();
assert.equal(await page.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('dxd-character-history-v1:')).length),0);
await page.reload({waitUntil:'networkidle'});assert.ok(await page.getByRole('button',{name:'Undo',exact:true}).isDisabled());
console.log('PASS size budget and disable preference');
assert.deepEqual(errors,[]);await browser.close();
